export const xlsxCellMap: Record<string, string> = {
  C2: "workstationEndpointProtection",
  D2: "workstationEndpointProtectionQuantity",
  E2: "workstationEndpointProtectionComment",
  C3: "workstationEndpointTechnology",
  D3: "workstationEndpointTechnologyQuantity",
  E3: "workstationEndpointTechnologyComment",
  C4: "workstationEndpointLicense",
  D4: "workstationEndpointLicenseQuantity",
  E4: "workstationEndpointLicenseComment",
  C5: "serverEndpointProtection",
  D5: "serverEndpointProtectionQuantity",
  E5: "serverEndpointProtectionComment",
  C6: "serverEndpointTechnology",
  D6: "serverEndpointTechnologyQuantity",
  E6: "serverEndpointTechnologyComment",
  C7: "endpointAndServerCounts",
  D7: "endpointAndServerCountsQuantity",
  E7: "endpointAndServerCountsComment",

  C13: "fortinet",
  C14: "paloAlto",
  C15: "sophos",
  C16: "cisco",
  C17: "sangfor",
  C18: "cloudflareWaf",
  C19: "awsWaf",
  C20: "sase",
  C21: "swg",
  C22: "dlp",
  C23: "otherSecurityTools",
  C24: "mdrTelemetryWanted",
  C25: "estimatedLogVolume",
  C26: "logVolumeBreakdown",

  C40: "aws",
  C41: "azure",
  C42: "gcp",
  C43: "cloudAndLoggingServices",
  C44: "thirdPartyCloudSecurity",

  C50: "entraId",
  C51: "okta",
  C52: "pingIdentity",
  C53: "oneLogin",
  C54: "ciamPamIga",
  C55: "cloudNativeIam",
  C56: "secretsMachineIdentity",
  C57: "zeroTrustItdr",

  C61: "siemExisting",
  C62: "siemDeployment",
  C63: "soarAndCurrentUsage",
  C64: "logSourcesAndSoc",
  C65: "coverageAndResponse",

  C70: "onPremEmail",
  C71: "cloudEmail",
  C72: "emailSecurity",
  C78: "identitySaaS",
  C79: "securitySaaS",
  C80: "productivitySaaS",
  C81: "crmSaaS",
  C82: "financeSaaS",
  C83: "hrSaaS",
  C84: "devopsSaaS",
  C85: "dataSaaS",
  C86: "ecommerceSaaS",
  C87: "itsmSaaS",
  C88: "otherSaaS",
  C93: "digitalRiskProtection",
  C94: "attackSurfaceManagement",
}
